---
- name: Include services installation task
  include_tasks: install_services.yml
  
- name: Install forensics tools
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ linux_forensics_tools }}"